server:
  port: 8080
spring:
  application:
    name: order-feign-hystrix80
eureka:
 client:
  register-with-eureka: true #禁止自己当做服务注册
  fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
  service-url:
   defaultZone: http://eureka7001.com:7001/eureka/
feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。打开feign对hystrix的支持 eignClient 中的 fallback