server:
  port: 3001
#服务名字
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #git 仓库的地址
          uri: https://github.com/psfloveni/springcloud-config.git
          #git 仓库的账号密码
          search-paths:
            - springcloud-config

#加入注册中心，实现高可用
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'