server:
  port: 8080
spring:
  application:
    name: springcloud-order80 #服务名称
#eureka client配置
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
