server:
  port: 8080
spring:
  application:
    name: springcloud-sleuth-order80 #服务名称
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
    probability: 1



#eureka client配置
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
